### ISSUE TITLE
Google Map Settings of Contact Form Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/coming-soon-master#11]
Hi Sandeep,
Here are the tasks for you for the Google Map Settings of Contact Form Page/Screen-
• Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
• Validate the fields marked with a star.
• Please make sure that the page properly updates all the default addresses to the meta tables.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy4** [comment]
# Changed Files: 
1. includes/footer.php
2. lib/action-library.php
3. views/contact-form/google-map-settings/google-map-settings.php

# Issues Fixed:
1. Validations are given on text fields.
2. All the default addresses of the meta tables has been updated successfully.
3. Loader and toaster notifications are working properly.
   
   Note: Reported issues are fixed.So this issue is marked as closed.

# Changed By: 

Sandeep

**Comment by tech-prodigy4** [comment]
# Changed Files:
1. includes/footer.php
2. lib/action-library.php
3. views/contact-form/google-map-settings/google-map-settings.php

# Issues Fixed:
1. Validations are given on text fields.
2. All the default addresses of the meta tables has been updated successfully.
3. Loader and toster notifications are working properly.
4. Page updates all values to meta table
5. Toster notification shown after click on save setting
6. Loader Works properly and refreshes the page after the update.
7. All the feilds are sanitized properly
   
   Note: Reported issues are fixed.So this issue is marked as closed.
   
   Changed By:
   
   Sandeep Kaur
