### ISSUE TITLE
Success Settings of the Subscription Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/coming-soon-master#14]
Hi Shiffi,

Here are the tasks for you for the Success Settings of the Subscription Page/Screen.

• Please make sure that the page properly reads all the default settings from the meta table and displays on the  screen in respective columns.
• Remove mandatory mark(*) from Custom CSS field.
• Validate the fields marked with a star.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards
Priyanka S.
Team Leader

**Comment by tech-prodigy2** [comment]
Hello Shiffi,
Please work on above mentioned issue(#14) which was earlier assigned to Ajay.

Note: Ajay, No need to work on above mentioned issue(#14)

**Comment by tech-prodigy5** [comment]
# Changed Files: 
1. includes\footer.php
2. lib\action-library
3. views\subscription\success-setting\success-setting.php

# Issues Fixed:
1. Page read all the default data from the database
2. Mandatory mark \* removed from custom css
3. Validation done on field marked with *
4. Page updates all values to meta table
5. Toster notification shown after click on save setting
6. Loader Works properly and refreshes the page after the update.
7. All the feilds are sanitized properly

Note: Reported issues are fixed. So this issue is marked as closed

Changed by:

Shiffi
