### ISSUE TITLE
 Heading Settings of the Layout settings Page/Screen.

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/coming-soon-master#24]
Hi Nancy

Here are the tasks for you for the Heading Settings of the Layout settings Page/Screen.

• Please make sure that the page properly reads all the default settings from the meta table and displays on the  screen in respective columns.
• Remove mandatory mark(*) from Custom CSS field.
• Validate the fields marked with a star.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and   needed.

Regards
Priyanka S.
Team Leader

**Comment by tech-prodigy9** [comment]
Issue ID: #24 Changes made at 05:55 PM

Changed Files:

```
1. includes/footer.php
2. lib/action-library.php
3. views/layout-settings/heading-settings/heading-settings.php
```

Issues Fixed:

```
1. Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
2. Remove mandatory mark(*) from Custom CSS field.
```

• Validate the fields marked with a star.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.

Note: Reported issues are fixed.So this issue is marked as closed.

Changed By:
Nancy Singla
